### ISSUE TITLE
Location marker doesn't move until you refresh

### ISSUE THREAD

**Issue by nnpoke** [PokemonGoMap/PokemonGo-Map#339]
When changing location with the edit field the map moves correctly to the new position. But the location marker remains on the old location until you refresh the web page.

## Expected Behavior
When changing location with the edit field the marker should update too without the need to refresh.

## Current Behavior
The marker doesn't move until you refresh the web page.

## Steps to Reproduce (for bugs)
1. Enter a new address in the location field and press enter.
2. The map moves but not the marker.
3. Refresh the page and the marker moves

## Your Environment
Ubuntu with latest version from GitHub. Tested on Windows and iOS (IE, Chrome and Safari)

**Comment by tkSimon** [comment]
hi, this should've been fixed by #164 about 7 hours ago.
could you please update and gibe it another try?

**Comment by tkSimon** [comment]
(my comment assumes that you mean the search marker - the read pin, not the blue 'my location' marker)

**Comment by nnpoke** [comment]
Yes it was the red pin (scan center). I can confirm it works now, Thank you.

**Comment by moleeternal** [comment]
I see this is closed.  I am using the most up to date development branch and this is still an issue for me.  Red location marker will not appear until I've refreshed the page.

**Comment by tkSimon** [comment]
Are you sure you ran `grunt build` after pulling the latest changes from git?

**Comment by moleeternal** [comment]
@tkSimon I thought I did.  But I just ran through everything again and it seems to me working.  Whatever it was, I'm good now! :D
